<?php
$code = 'aW5jbHVkZSAiQWluay5waHAiOw0KZWNobyAiTWFzdWthbiBLb3RhIGFuZGEgOiAiOw0KJGtvdGEgPSB0cmltKGZnZXRzKFNURElOKSk7DQokdXJsID0gZmlsZV9nZXRfY29udGVudHMoImh0dHBzOi8vdGltZS5zaXN3YWRpLmNvbS9wcmF5LyRrb3RhIik7DQokdXJsMSA9IGV4cGxvZGUoIjxicj4iLCAkdXJsKTsNCmZvcmVhY2ggKCR1cmwxIGFzICRrZXkpew0KJGpzID0ganNvbl9kZWNvZGUoJGtleSwgdHJ1ZSk7DQpwcmludF9yKCRqcyk7DQp9';
eval(base64_decode($code));
?>
